name: CI

on: pull_request
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Environment setup
      run: sudo apt-get update && sudo apt-get -y install ant ant-contrib	autoconf bash apt-transport-https ca-certificates dirmngr git make zip wget
    - name: GetJDK
      uses: TheMrMilchmann/install-jdk@v1
      with:
        version: '8'
        architecture: x64
    - name: Run tests
      uses: skx/github-action-tester@master 
      with:
      script: .github/fast-tests.sh
